### ISSUE TITLE
Feature request: constructing ElapsedTime

### ISSUE THREAD

**Issue by hanna-kruppe** [matklad/elapsed#1]
This crate is virtually identical to some one-off code lying around in one of my projects, so I'd love to use it and get rid of said code :) There's just one problem: One duration I want to print is not measured but computed (from a measured duration, FWIW). So I'd need a way to create an `ElapsedDuration` from a `Duration`. Does this look reasonable to you?

**Comment by matklad** [comment]
Sounds reasonable!

Does this implementation look good https://github.com/matklad/elapsed/commit/95b5bf803379dc0425ad8796348776deb7edff0c?

We can probably add a `From` impl, but I usually find that `new` is enough, and it's simpler.

**Comment by hanna-kruppe** [comment]
`new` is fine, thanks for the quick reaction! https://github.com/rkruppe/suptracer/commit/2a79824ccf7670a3349ee515d1340a4736db2a22
